### ISSUE TITLE
[WIP] User experience check

### ISSUE THREAD

**Issue by diimpp** [rollerworks/RollerworksMultiUserBundle#77]
Hi,

I'm trying this bundle and starting to encounter some issues. 
So I will keep this as meta issue for questions & fixes.

- FOSUser mapping use different folder for it's mappings #76 
- GenerateUserSysCommand compatibility with sf2.3 issue #78
- Fix errors translation of security login page #80

**Comment by diimpp** [comment]
Sorry, can't find time to do doc fixes.
Still thread somewhat documenting itself  :smile: 

Thank you on your assistance with this one :)

**Comment by sstok** [comment]
No problem :)
