### ISSUE TITLE
overriding template of each user bundle

### ISSUE THREAD

**Issue by gholami-mohammad** [rollerworks/RollerworksMultiUserBundle#90]
when you create many user bundle under rollerworkers , we cant override template of each bundle separately!

**Comment by sstok** [comment]
Actually you can, the documentation is a big problem (and I don't have any time to get this resolved).

Each user-bundle you create has its own configuration, see https://github.com/rollerworks/RollerworksMultiUserBundle/blob/master/docs/creating_classes_by_hand.md#34-make-your-bundle-configurable for a complete reference. You can set the template location to overwrite the template for your user-bundle.
