### ISSUE TITLE
resetting password request NOT WORKING

### ISSUE THREAD

**Issue by gholami-mohammad** [rollerworks/RollerworksMultiUserBundle#91]
in rollerworker ressetting/request have an error below:
Variable "form" does not exist in RollerworksMultiUserBundle:UserBundle/Resetting:request_content.html.twig at line 3

500 Internal Server Error - Twig_Error_Runtime

How to solve this?

**Comment by sstok** [comment]
Can you try the latest dev-master? and confirm this is fixed by 881dff7dfa381cdf6104d460fa2a37d13f22ec1d

**Comment by gholami-mohammad** [comment]
I change request_content.html.twig as your guid https://github.com/rollerworks/RollerworksMultiUserBundle/commit/881dff7dfa381cdf6104d460fa2a37d13f22ec1d

I made some changes in your bundle , I cant install dev-master!
