### ISSUE TITLE
not redirect to correct firewall after session timout

### ISSUE THREAD

**Issue by gholami-mohammad** [rollerworks/RollerworksMultiUserBundle#92]
Hi
I have 2 user type in system. when I try to access an secured area(when I am not logged in) it always redirect me to 127.0.0.1:8000/login
but it must redirect me to 127.0.0.1:8000 /admin/login.
How can I fix this?

```
first_firewall:
   pattern: /admin
   ...
second_firewall:
  pattern: /user
  ....
```

in second_firewall I dont have this problem

**Comment by sstok** [comment]
The RollerworksMultiUserBundle is designed to support multiple user-systems with the FOSUserBundle.
But neither the RollerworksMultiUserBundle or FOSUserBundle has anything to do with the Security Firewall.

This seems more like a general Symfony usage question, and I can't help you with this (sorry).
You can get support for Symfony at https://stackoverflow.com/ or the `#Symfony` IRC channel https://symfony.com/irc
