### ISSUE TITLE
Overriding templates

### ISSUE THREAD

**Issue by mondot** [rollerworks/RollerworksMultiUserBundle#93]
Hi,

Be careful of the "Note:" at the end of the doc Overriding Default RollerworksMultiUserBundle Templates. 
It says :"Unlike the FOSUserBundle, templates should be placed inside the src/Acme/UserBundle/Resources/views/UserBundle. Failing to do so will break the automatic loading of the configured template." 

But it didn't work for me. 

Instead, it works well when I placed my templates in src/Acme/UserBundle/Resources/views/ as I did for overriding FOSUserBundle templates. 

Anyway, thanks for your work on the Bundle, it really helps !

**Comment by sstok** [comment]
Good catch :) this section is about overwriting the global templates (not the onces of your user-bundle).

**Comment by mondot** [comment]
I noticed that your "Note:" was usefull if you use two types of Users. 

In fact, I tried to create an other UserBundle (which I'll call UserB), and when I wanted to use my new templates for this UserB, I always had the ones for UserA. 

To fix that, I had to take off the getParent() function in my UserA AcmeUserBundle.php, and I had to change the template path in AcmeUserExtension.php (for UserA and UserB). In that way, I had to place my templates inside the src/Acme/UserBundle/Resources/views/UserBundle to make it work. 

Conclusion : the "Note:" is usefull when you don't use the function getParent() in your AcmeUserBundle.php and that you have two UserBundles. 

So, when you have two different UserBundles, you won't use getParent() function. 

(now I have an other problem when I try to logout, it tells me "You must activate the logout in your security firewall configuration." and currently I don't succeed to do it for my two UserBundles (UserA and UserB). Can you show me how to configure my firewall if I have two different users please ?)

**Comment by sstok** [comment]
I improved it in ba8e89e5eb19db5d2ed50ed92be846fd309a5dc9 :)

**Comment by mondot** [comment]
It seems better :) 

I am still on my firewall issue. 
When I change the 'firewall_name' => 'UserA' (line 71 in AcmeUserAExtension.php), it doesn't change anything (even if I have my userA firewall configured in security.yml). It always uses the "main" firewall with the pattern ^/ .

Have you an idea why ? 

Currently I can just configure my "main" firewall with the pattern ^/, the other firewalls are not used. So I can just have one UserBundle well configured :/

**Comment by sstok** [comment]
The registration order of the firewalls is really important, if you register main `^/` first it will match everything. You need place the firewall with the most precise pattern (eg. `^/user/something`) at the top.

```
userA: ^/users/something/
userB: ^/users/
main: ^/
```

**Comment by mondot** [comment]
Great it works, 

thanks :)
